# The name of your Cloudflare Worker project
name = "restate-cloudflare-worker"

# Entrypoint
main = "./src/index.ts"

# Preview URLs are used to register to Restate
preview_urls = true

# Enable NodeJS compatibility (used by the SDK for the Node Buffer API)
# and Node's process.env (for logging)
compatibility_date = "2025-09-23"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]